export const PLANET_DATA = {
  Sun: {
    color: '#ffd600',
    description: 'The Sun is the star at the center of our Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core, converting hydrogen into helium.',
    details: {
      'Type': 'G2V Yellow Dwarf',
      'Diameter': '1,391,000 km',
      'Mass': '1.989 × 10³⁰ kg',
      'Surface Temp': '5,500°C',
      'Core Temp': '~15,000,000°C',
      'Age': '4.6 billion years',
      'Distance from Earth': '149.6 million km',
    },
    funFact: 'The Sun contains 99.86% of all mass in the Solar System. About one million Earths could fit inside it!',
  },
  Mercury: {
    color: '#a8a8a8',
    description: 'Mercury is the smallest planet in our Solar System and the closest to the Sun. It has virtually no atmosphere to retain heat, causing extreme temperature swings.',
    details: {
      'Diameter': '4,879 km',
      'Mass': '3.301 × 10²³ kg',
      'Gravity': '3.7 m/s²',
      'Day Length': '58.6 Earth days',
      'Year Length': '88 Earth days',
      'Moons': '0',
      'Avg Temperature': '-180 to 430°C',
    },
    funFact: 'A year on Mercury is just 88 Earth days, but a day lasts 59 Earth days — almost two-thirds of a year!',
  },
  Venus: {
    color: '#e8c84a',
    description: 'Venus is the hottest planet in the Solar System due to a runaway greenhouse effect. It rotates backwards compared to most other planets.',
    details: {
      'Diameter': '12,104 km',
      'Mass': '4.867 × 10²⁴ kg',
      'Gravity': '8.87 m/s²',
      'Day Length': '243 Earth days',
      'Year Length': '225 Earth days',
      'Moons': '0',
      'Avg Temperature': '462°C (surface)',
    },
    funFact: 'Venus rotates so slowly that its day is longer than its year! It also spins in the opposite direction to most planets.',
  },
  Earth: {
    color: '#4d9de0',
    description: 'Earth is the third planet from the Sun and the only known world to harbor life. Its liquid surface water, magnetic field, and atmosphere make it uniquely habitable.',
    details: {
      'Diameter': '12,756 km',
      'Mass': '5.972 × 10²⁴ kg',
      'Gravity': '9.81 m/s²',
      'Day Length': '24 hours',
      'Year Length': '365.25 days',
      'Moons': '1',
      'Avg Temperature': '-89 to 57°C',
    },
    funFact: 'Earth is the only planet not named after a Greek or Roman god. About 71% of its surface is covered in water!',
  },
  Mars: {
    color: '#e07050',
    description: 'Mars is known as the Red Planet due to iron oxide (rust) on its surface. It has the tallest mountain and the longest canyon in the Solar System.',
    details: {
      'Diameter': '6,792 km',
      'Mass': '6.417 × 10²³ kg',
      'Gravity': '3.72 m/s²',
      'Day Length': '24.6 hours',
      'Year Length': '687 Earth days',
      'Moons': '2 (Phobos & Deimos)',
      'Avg Temperature': '-87 to -5°C',
    },
    funFact: 'Olympus Mons on Mars is the largest volcano in the Solar System — 2.5 times taller than Mount Everest!',
  },
  Jupiter: {
    color: '#d4a574',
    description: 'Jupiter is the largest planet in the Solar System — a gas giant with no solid surface. Its Great Red Spot is a storm larger than Earth that has raged for centuries.',
    details: {
      'Diameter': '142,984 km',
      'Mass': '1.898 × 10²⁷ kg',
      'Gravity': '24.79 m/s²',
      'Day Length': '9.9 hours',
      'Year Length': '11.86 Earth years',
      'Moons': '95',
      'Avg Temperature': '-110°C (cloud top)',
    },
    funFact: 'Jupiter\'s Great Red Spot is a storm larger than Earth that has been raging for at least 400 years!',
  },
  Saturn: {
    color: '#e8d5a3',
    description: 'Saturn is famous for its spectacular ring system made of ice and rock particles. It is the least dense planet — it would float in water if you found a big enough pool.',
    details: {
      'Diameter': '120,536 km',
      'Mass': '5.683 × 10²⁶ kg',
      'Gravity': '10.44 m/s²',
      'Day Length': '10.7 hours',
      'Year Length': '29.46 Earth years',
      'Moons': '146',
      'Avg Temperature': '-140°C',
    },
    funFact: 'Saturn\'s density is so low (0.687 g/cm³) that it would actually float in water! Its rings span up to 282,000 km but are only about 10 meters thick.',
  },
  Uranus: {
    color: '#7ec8e3',
    description: 'Uranus is an ice giant with a blue-green color from methane in its atmosphere. It rotates on its side, possibly from a massive ancient collision.',
    details: {
      'Diameter': '51,118 km',
      'Mass': '8.681 × 10²⁵ kg',
      'Gravity': '8.87 m/s²',
      'Day Length': '17.2 hours',
      'Year Length': '84 Earth years',
      'Moons': '27',
      'Avg Temperature': '-195°C',
    },
    funFact: 'Uranus rotates on its side with an axial tilt of 98°, essentially rolling around the Sun like a ball!',
  },
  Neptune: {
    color: '#3f54ba',
    description: 'Neptune is the windiest planet in the Solar System, with gusts reaching 2,100 km/h. It is the farthest and coldest planet from the Sun.',
    details: {
      'Diameter': '49,528 km',
      'Mass': '1.024 × 10²⁶ kg',
      'Gravity': '11.15 m/s²',
      'Day Length': '16.1 hours',
      'Year Length': '164.8 Earth years',
      'Moons': '16',
      'Avg Temperature': '-200°C',
    },
    funFact: 'Neptune has the strongest winds in the Solar System, reaching speeds of 2,100 km/h — faster than any storm on Earth!',
  },
};
