export const MOON_INFO = {
  Moon: {
    color: '#c8c8c8',
    description: 'The Moon is Earth\'s only natural satellite and the fifth largest moon in the Solar System. Formed about 4.5 billion years ago, it drives Earth\'s tides and stabilizes our axial tilt.',
    details: {
      'Diameter': '3,475 km',
      'Distance from Planet': '384,400 km',
      'Orbital Period': '27.3 days',
      'Gravity': '1.62 m/s²',
      'Surface Temp': '-173 to 127°C',
    },
    funFact: 'The Moon is drifting away from Earth by about 3.8 centimeters every year — roughly the speed our fingernails grow!',
  },
  Lunar: {
    color: '#c8c8c8',
    description: 'Earth\'s natural satellite in this simulation — one of the largest moons in the Solar System and the only natural satellite of a terrestrial world.',
    details: {
      'Diameter': '3,475 km',
      'Distance from Planet': '384,400 km',
      'Orbital Period': '27.3 days',
      'Gravity': '1.62 m/s²',
    },
    funFact: 'The Moon always shows the same face to Earth — its rotation is tidally locked!',
  },
  Phobos: {
    color: '#9a8f80',
    description: 'Phobos is the larger and closer of Mars\' two moons. It is a heavily cratered, potato-shaped body that orbits Mars faster than the planet itself rotates.',
    details: {
      'Diameter': '22.5 km',
      'Distance from Planet': '6,000 km',
      'Orbital Period': '7.7 hours',
      'Gravity': '0.0057 m/s²',
    },
    funFact: 'From the surface of Mars, Phobos rises in the west and sets in the east — sometimes twice a day!',
  },
  Deimos: {
    color: '#a59a8a',
    description: 'Deimos is the smaller and more distant of Mars\' two moons. Its surface is smoother than Phobos, mostly covered by a thick layer of loose regolith.',
    details: {
      'Diameter': '12.4 km',
      'Distance from Planet': '23,500 km',
      'Orbital Period': '30.3 hours',
      'Gravity': '0.003 m/s²',
    },
    funFact: 'Deimos is so small and faint that a casual observer on Mars might mistake it for a bright star!',
  },
  Io: {
    color: '#d8b84a',
    description: 'Io is the most volcanically active body in the Solar System. Jupiter\'s intense gravity flexes the moon, generating internal heat that powers hundreds of active volcanoes.',
    details: {
      'Diameter': '3,643 km',
      'Distance from Planet': '421,700 km',
      'Orbital Period': '1.77 days',
      'Gravity': '1.80 m/s²',
    },
    funFact: 'Io\'s volcanoes shoot plumes of sulfur up to 300 km above its surface — the tallest mountains there dwarf Mount Everest!',
  },
  Europa: {
    color: '#d8d0c0',
    description: 'Europa is an icy moon with a subsurface ocean that may hold twice as much water as all of Earth\'s oceans combined — a prime candidate for hosting extraterrestrial life.',
    details: {
      'Diameter': '3,122 km',
      'Distance from Planet': '671,000 km',
      'Orbital Period': '3.55 days',
      'Gravity': '1.31 m/s²',
    },
    funFact: 'Under Europa\'s cracked ice crust lies a salty ocean about 100 km deep, kept liquid by Jupiter\'s tidal heating!',
  },
  Ganymede: {
    color: '#b8aa98',
    description: 'Ganymede is the largest moon in the Solar System — bigger than the planet Mercury. It is the only moon known to generate its own magnetic field.',
    details: {
      'Diameter': '5,268 km',
      'Distance from Planet': '1,070,400 km',
      'Orbital Period': '7.15 days',
      'Gravity': '1.43 m/s²',
    },
    funFact: 'If Ganymede orbited the Sun instead of Jupiter, it would qualify as a planet — it\'s larger than Mercury!',
  },
  Callisto: {
    color: '#8f8578',
    description: 'Callisto is the most heavily cratered object in the Solar System. Its ancient, inactive surface has remained nearly unchanged for over four billion years.',
    details: {
      'Diameter': '4,821 km',
      'Distance from Planet': '1,882,700 km',
      'Orbital Period': '16.7 days',
      'Gravity': '1.24 m/s²',
    },
    funFact: 'Callisto\'s surface is so old that it records the entire bombardment history of the early Solar System!',
  },
  Mimas: {
    color: '#d0d0d0',
    description: 'Mimas is a small, heavily cratered moon of Saturn. A giant impact crater makes it eerily resemble the Death Star from Star Wars.',
    details: {
      'Diameter': '396 km',
      'Distance from Planet': '185,000 km',
      'Orbital Period': '0.94 days',
      'Gravity': '0.064 m/s²',
    },
    funFact: 'The crater Herschel on Mimas is 139 km wide — one-third of the moon\'s entire diameter!',
  },
  Enceladus: {
    color: '#f0f0f0',
    description: 'Enceladus is one of the most reflective bodies in the Solar System. Geysers at its south pole shoot water vapor into space, feeding Saturn\'s E ring.',
    details: {
      'Diameter': '504 km',
      'Distance from Planet': '238,000 km',
      'Orbital Period': '1.37 days',
      'Gravity': '0.113 m/s²',
    },
    funFact: 'Enceladus is almost pure white because its entire surface is coated in fresh ice from active geysers!',
  },
  Tethys: {
    color: '#d8d8d8',
    description: 'Tethys is an icy Saturnian moon with a vast canyon system called Ithaca Chasma that spans most of its surface. It shares its orbit with two small co-orbital moons.',
    details: {
      'Diameter': '1,062 km',
      'Distance from Planet': '294,700 km',
      'Orbital Period': '1.89 days',
      'Gravity': '0.15 m/s²',
    },
    funFact: 'Ithaca Chasma on Tethys stretches for 2,000 km — it would wrap most of the way around Earth!',
  },
  Dione: {
    color: '#c8c8c8',
    description: 'Dione is an icy Saturnian moon with wispy white ice cliffs and a thin oxygen atmosphere. It leads a smaller moon, Helene, in its orbit.',
    details: {
      'Diameter': '1,123 km',
      'Distance from Planet': '377,400 km',
      'Orbital Period': '2.74 days',
      'Gravity': '0.232 m/s²',
    },
    funFact: 'Dione has razor-thin cliffs of bright ice — some of the most dramatic scenery in the Saturn system!',
  },
  Rhea: {
    color: '#c0c0c0',
    description: 'Rhea is Saturn\'s second-largest moon, a heavily cratered icy world. It is the only moon confirmed to have a tenuous ring system of its own.',
    details: {
      'Diameter': '1,527 km',
      'Distance from Planet': '527,100 km',
      'Orbital Period': '4.52 days',
      'Gravity': '0.264 m/s²',
    },
    funFact: 'Rhea may have a faint ring of its own — the only moon known to be ringed!',
  },
  Titan: {
    color: '#d8a850',
    description: 'Titan is Saturn\'s largest moon and the only moon with a thick atmosphere. Its surface hosts rivers and lakes of liquid methane beneath a hazy orange sky.',
    details: {
      'Diameter': '5,150 km',
      'Distance from Planet': '1,221,900 km',
      'Orbital Period': '15.9 days',
      'Gravity': '1.35 m/s²',
      'Atmosphere': '1.45x denser than Earth\'s',
    },
    funFact: 'Titan is the only place beyond Earth where standing liquid has been found — lakes of liquid methane and ethane!',
  },
  Iapetus: {
    color: '#8a8078',
    description: 'Iapetus is Saturn\'s strange two-toned moon — one hemisphere is as dark as coal while the other gleams nearly as white as snow. A 20 km tall equatorial ridge circles its equator.',
    details: {
      'Diameter': '1,470 km',
      'Distance from Planet': '3,560,800 km',
      'Orbital Period': '79.3 days',
      'Gravity': '0.223 m/s²',
    },
    funFact: 'The equatorial ridge on Iapetus makes it look like a giant walnut — its origin remains a mystery!',
  },
  Miranda: {
    color: '#c8c8c8',
    description: 'Miranda is the smallest of Uranus\' large moons but the most geologically bizarre, featuring towering cliffs and diverse terrain unlike anything else in the Solar System.',
    details: {
      'Diameter': '472 km',
      'Distance from Planet': '129,900 km',
      'Orbital Period': '1.41 days',
      'Gravity': '0.079 m/s²',
    },
    funFact: 'Verona Rupes on Miranda is a cliff up to 20 km deep — visitors could free-fall down it for 12 minutes!',
  },
  Ariel: {
    color: '#d8d0c8',
    description: 'Ariel is the brightest of Uranus\' large moons. Its youthful, fractured surface with canyons and smooth plains suggests active resurfacing in the past.',
    details: {
      'Diameter': '1,158 km',
      'Distance from Planet': '190,900 km',
      'Orbital Period': '2.52 days',
      'Gravity': '0.269 m/s²',
    },
    funFact: 'Ariel has some of the youngest-looking surfaces among Uranus\' moons — barely cratered and crisscrossed with valleys!',
  },
  Umbriel: {
    color: '#8f8f8f',
    description: 'Umbriel is the darkest of Uranus\' large moons and one of the most heavily cratered. Its ancient, uniform surface has changed little since the early Solar System.',
    details: {
      'Diameter': '1,169 km',
      'Distance from Planet': '266,000 km',
      'Orbital Period': '4.14 days',
      'Gravity': '0.2 m/s²',
    },
    funFact: 'Umbriel is so dark it reflects only about half the light that its brighter sibling Ariel does!',
  },
  Titania: {
    color: '#d0d0c8',
    description: 'Titania is the largest moon of Uranus, with a network of rift valleys and a surface heavily cratered but also resurfaced in parts. It may hold a subsurface ocean.',
    details: {
      'Diameter': '1,578 km',
      'Distance from Planet': '436,300 km',
      'Orbital Period': '8.71 days',
      'Gravity': '0.378 m/s²',
    },
    funFact: 'Titania\'s canyons rival the Grand Canyon in depth — some drops reach 5 km!',
  },
  Oberon: {
    color: '#b8b0a8',
    description: 'Oberon is the outermost of Uranus\' large moons. Its heavily cratered, ancient surface may hide a buried subsurface ocean between core and icy crust.',
    details: {
      'Diameter': '1,523 km',
      'Distance from Planet': '583,500 km',
      'Orbital Period': '13.5 days',
      'Gravity': '0.346 m/s²',
    },
    funFact: 'Oberon is the second-most heavily cratered moon of Uranus — its surface records eons of impacts!',
  },
  Triton: {
    color: '#d8d0d8',
    description: 'Triton is Neptune\'s largest moon and one of the coldest known worlds. It orbits backwards, meaning it probably formed elsewhere and was captured by Neptune\'s gravity.',
    details: {
      'Diameter': '2,707 km',
      'Distance from Planet': '354,800 km',
      'Orbital Period': '5.88 days',
      'Gravity': '0.779 m/s²',
      'Surface Temp': '-235°C',
    },
    funFact: 'Triton is slowly spiraling toward Neptune — in billions of years it will be torn apart into a ring!',
  },
  Nereid: {
    color: '#a8a8a8',
    description: 'Nereid is one of the most eccentric moons in the Solar System — its orbit carries it from just two million km to nearly ten million km from Neptune.',
    details: {
      'Diameter': '340 km',
      'Distance from Planet': '5,513,400 km',
      'Orbital Period': '360.1 days',
      'Gravity': '0.07 m/s²',
    },
    funFact: 'Nereid has the most eccentric orbit of any known major moon — it swings almost a year-long arc around Neptune!',
  },
};